main:
  - title: "Spring Cert"
    url: /spring/container/
  - title: "Билдирүүлөр"
    url: /posts/
  - title: "Катерогиялар"
    url: /categories/
  - title: "Тэгдер"
    url: /tags/
  - title: "Блог жөнүндө"
    url: /about/

spring:
  - title: "Exam Topics"
    children:
      - title: "Container"
        url: /spring/container/
      - title: "AOP"
        url: /spring/aop/